// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Y3ophkDHYBqwDqg51CTpGRTPkNCy_po',
    appId: '1:384867838662:web:db4c2031f630a804ca05c7',
    messagingSenderId: '384867838662',
    projectId: 'bidna-337a4',
    authDomain: 'bidna-337a4.firebaseapp.com',
    storageBucket: 'bidna-337a4.firebasestorage.app',
    measurementId: 'G-M89PLJLBNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAukl4o7sNy175D4idE92UzpNpjIAuiOb8',
    appId: '1:384867838662:android:9040afa1b2d57fd3ca05c7',
    messagingSenderId: '384867838662',
    projectId: 'bidna-337a4',
    storageBucket: 'bidna-337a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5OYlcTUp2pdNuzrQ7Nm8VOqZt_5ASBE',
    appId: '1:384867838662:ios:3e56c800e2ef7709ca05c7',
    messagingSenderId: '384867838662',
    projectId: 'bidna-337a4',
    storageBucket: 'bidna-337a4.firebasestorage.app',
    iosBundleId: 'com.example.bidna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5OYlcTUp2pdNuzrQ7Nm8VOqZt_5ASBE',
    appId: '1:384867838662:ios:3e56c800e2ef7709ca05c7',
    messagingSenderId: '384867838662',
    projectId: 'bidna-337a4',
    storageBucket: 'bidna-337a4.firebasestorage.app',
    iosBundleId: 'com.example.bidna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Y3ophkDHYBqwDqg51CTpGRTPkNCy_po',
    appId: '1:384867838662:web:3ad8f6796e7418dcca05c7',
    messagingSenderId: '384867838662',
    projectId: 'bidna-337a4',
    authDomain: 'bidna-337a4.firebaseapp.com',
    storageBucket: 'bidna-337a4.firebasestorage.app',
    measurementId: 'G-875STD8Y1T',
  );
}
